title: Clinic Handbook
description: Movement and Memory Disorders Clinic

theme: just-the-docs

color_scheme: clinic

search_enabled: true

url: https://clue253.github.io
baseurl: "/movement-and-memory"
